/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ambiata.ivory.lookup;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class FeatureIdMapping implements org.apache.thrift.TBase<FeatureIdMapping, FeatureIdMapping._Fields>, java.io.Serializable, Cloneable, Comparable<FeatureIdMapping> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FeatureIdMapping");

  private static final org.apache.thrift.protocol.TField MAPPING_FIELD_DESC = new org.apache.thrift.protocol.TField("mapping", org.apache.thrift.protocol.TType.MAP, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new FeatureIdMappingStandardSchemeFactory());
    schemes.put(TupleScheme.class, new FeatureIdMappingTupleSchemeFactory());
  }

  public Map<String,FeatureMappingValue> mapping; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MAPPING((short)1, "mapping");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MAPPING
          return MAPPING;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MAPPING, new org.apache.thrift.meta_data.FieldMetaData("mapping", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, FeatureMappingValue.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FeatureIdMapping.class, metaDataMap);
  }

  public FeatureIdMapping() {
  }

  public FeatureIdMapping(
    Map<String,FeatureMappingValue> mapping)
  {
    this();
    this.mapping = mapping;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FeatureIdMapping(FeatureIdMapping other) {
    if (other.isSetMapping()) {
      Map<String,FeatureMappingValue> __this__mapping = new HashMap<String,FeatureMappingValue>(other.mapping.size());
      for (Map.Entry<String, FeatureMappingValue> other_element : other.mapping.entrySet()) {

        String other_element_key = other_element.getKey();
        FeatureMappingValue other_element_value = other_element.getValue();

        String __this__mapping_copy_key = other_element_key;

        FeatureMappingValue __this__mapping_copy_value = new FeatureMappingValue(other_element_value);

        __this__mapping.put(__this__mapping_copy_key, __this__mapping_copy_value);
      }
      this.mapping = __this__mapping;
    }
  }

  public FeatureIdMapping deepCopy() {
    return new FeatureIdMapping(this);
  }

  @Override
  public void clear() {
    this.mapping = null;
  }

  public int getMappingSize() {
    return (this.mapping == null) ? 0 : this.mapping.size();
  }

  public void putToMapping(String key, FeatureMappingValue val) {
    if (this.mapping == null) {
      this.mapping = new HashMap<String,FeatureMappingValue>();
    }
    this.mapping.put(key, val);
  }

  public Map<String,FeatureMappingValue> getMapping() {
    return this.mapping;
  }

  public FeatureIdMapping setMapping(Map<String,FeatureMappingValue> mapping) {
    this.mapping = mapping;
    return this;
  }

  public void unsetMapping() {
    this.mapping = null;
  }

  /** Returns true if field mapping is set (has been assigned a value) and false otherwise */
  public boolean isSetMapping() {
    return this.mapping != null;
  }

  public void setMappingIsSet(boolean value) {
    if (!value) {
      this.mapping = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case MAPPING:
      if (value == null) {
        unsetMapping();
      } else {
        setMapping((Map<String,FeatureMappingValue>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case MAPPING:
      return getMapping();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case MAPPING:
      return isSetMapping();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof FeatureIdMapping)
      return this.equals((FeatureIdMapping)that);
    return false;
  }

  public boolean equals(FeatureIdMapping that) {
    if (that == null)
      return false;

    boolean this_present_mapping = true && this.isSetMapping();
    boolean that_present_mapping = true && that.isSetMapping();
    if (this_present_mapping || that_present_mapping) {
      if (!(this_present_mapping && that_present_mapping))
        return false;
      if (!this.mapping.equals(that.mapping))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(FeatureIdMapping other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetMapping()).compareTo(other.isSetMapping());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMapping()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mapping, other.mapping);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("FeatureIdMapping(");
    boolean first = true;

    sb.append("mapping:");
    if (this.mapping == null) {
      sb.append("null");
    } else {
      sb.append(this.mapping);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FeatureIdMappingStandardSchemeFactory implements SchemeFactory {
    public FeatureIdMappingStandardScheme getScheme() {
      return new FeatureIdMappingStandardScheme();
    }
  }

  private static class FeatureIdMappingStandardScheme extends StandardScheme<FeatureIdMapping> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, FeatureIdMapping struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MAPPING
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map50 = iprot.readMapBegin();
                struct.mapping = new HashMap<String,FeatureMappingValue>(2*_map50.size);
                for (int _i51 = 0; _i51 < _map50.size; ++_i51)
                {
                  String _key52;
                  FeatureMappingValue _val53;
                  _key52 = iprot.readString();
                  _val53 = new FeatureMappingValue();
                  _val53.read(iprot);
                  struct.mapping.put(_key52, _val53);
                }
                iprot.readMapEnd();
              }
              struct.setMappingIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, FeatureIdMapping struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.mapping != null) {
        oprot.writeFieldBegin(MAPPING_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, struct.mapping.size()));
          for (Map.Entry<String, FeatureMappingValue> _iter54 : struct.mapping.entrySet())
          {
            oprot.writeString(_iter54.getKey());
            _iter54.getValue().write(oprot);
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FeatureIdMappingTupleSchemeFactory implements SchemeFactory {
    public FeatureIdMappingTupleScheme getScheme() {
      return new FeatureIdMappingTupleScheme();
    }
  }

  private static class FeatureIdMappingTupleScheme extends TupleScheme<FeatureIdMapping> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FeatureIdMapping struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetMapping()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetMapping()) {
        {
          oprot.writeI32(struct.mapping.size());
          for (Map.Entry<String, FeatureMappingValue> _iter55 : struct.mapping.entrySet())
          {
            oprot.writeString(_iter55.getKey());
            _iter55.getValue().write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FeatureIdMapping struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TMap _map56 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.mapping = new HashMap<String,FeatureMappingValue>(2*_map56.size);
          for (int _i57 = 0; _i57 < _map56.size; ++_i57)
          {
            String _key58;
            FeatureMappingValue _val59;
            _key58 = iprot.readString();
            _val59 = new FeatureMappingValue();
            _val59.read(iprot);
            struct.mapping.put(_key58, _val59);
          }
        }
        struct.setMappingIsSet(true);
      }
    }
  }

}

