/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ambiata.ivory.core.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ThriftDictionaryList extends org.apache.thrift.TUnion<ThriftDictionaryList, ThriftDictionaryList._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftDictionaryList");
  private static final org.apache.thrift.protocol.TField ENCODING_FIELD_DESC = new org.apache.thrift.protocol.TField("encoding", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField STRUCT_ENCODING_FIELD_DESC = new org.apache.thrift.protocol.TField("structEncoding", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see ThriftDictionaryEncoding
     */
    ENCODING((short)1, "encoding"),
    STRUCT_ENCODING((short)2, "structEncoding");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ENCODING
          return ENCODING;
        case 2: // STRUCT_ENCODING
          return STRUCT_ENCODING;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ENCODING, new org.apache.thrift.meta_data.FieldMetaData("encoding", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, ThriftDictionaryEncoding.class)));
    tmpMap.put(_Fields.STRUCT_ENCODING, new org.apache.thrift.meta_data.FieldMetaData("structEncoding", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftDictionaryStruct.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftDictionaryList.class, metaDataMap);
  }

  public ThriftDictionaryList() {
    super();
  }

  public ThriftDictionaryList(_Fields setField, Object value) {
    super(setField, value);
  }

  public ThriftDictionaryList(ThriftDictionaryList other) {
    super(other);
  }
  public ThriftDictionaryList deepCopy() {
    return new ThriftDictionaryList(this);
  }

  public static ThriftDictionaryList encoding(ThriftDictionaryEncoding value) {
    ThriftDictionaryList x = new ThriftDictionaryList();
    x.setEncoding(value);
    return x;
  }

  public static ThriftDictionaryList structEncoding(ThriftDictionaryStruct value) {
    ThriftDictionaryList x = new ThriftDictionaryList();
    x.setStructEncoding(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, Object value) throws ClassCastException {
    switch (setField) {
      case ENCODING:
        if (value instanceof ThriftDictionaryEncoding) {
          break;
        }
        throw new ClassCastException("Was expecting value of type ThriftDictionaryEncoding for field 'encoding', but got " + value.getClass().getSimpleName());
      case STRUCT_ENCODING:
        if (value instanceof ThriftDictionaryStruct) {
          break;
        }
        throw new ClassCastException("Was expecting value of type ThriftDictionaryStruct for field 'structEncoding', but got " + value.getClass().getSimpleName());
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case ENCODING:
          if (field.type == ENCODING_FIELD_DESC.type) {
            ThriftDictionaryEncoding encoding;
            encoding = ThriftDictionaryEncoding.findByValue(iprot.readI32());
            return encoding;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case STRUCT_ENCODING:
          if (field.type == STRUCT_ENCODING_FIELD_DESC.type) {
            ThriftDictionaryStruct structEncoding;
            structEncoding = new ThriftDictionaryStruct();
            structEncoding.read(iprot);
            return structEncoding;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case ENCODING:
        ThriftDictionaryEncoding encoding = (ThriftDictionaryEncoding)value_;
        oprot.writeI32(encoding.getValue());
        return;
      case STRUCT_ENCODING:
        ThriftDictionaryStruct structEncoding = (ThriftDictionaryStruct)value_;
        structEncoding.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case ENCODING:
          ThriftDictionaryEncoding encoding;
          encoding = ThriftDictionaryEncoding.findByValue(iprot.readI32());
          return encoding;
        case STRUCT_ENCODING:
          ThriftDictionaryStruct structEncoding;
          structEncoding = new ThriftDictionaryStruct();
          structEncoding.read(iprot);
          return structEncoding;
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case ENCODING:
        ThriftDictionaryEncoding encoding = (ThriftDictionaryEncoding)value_;
        oprot.writeI32(encoding.getValue());
        return;
      case STRUCT_ENCODING:
        ThriftDictionaryStruct structEncoding = (ThriftDictionaryStruct)value_;
        structEncoding.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case ENCODING:
        return ENCODING_FIELD_DESC;
      case STRUCT_ENCODING:
        return STRUCT_ENCODING_FIELD_DESC;
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  /**
   * 
   * @see ThriftDictionaryEncoding
   */
  public ThriftDictionaryEncoding getEncoding() {
    if (getSetField() == _Fields.ENCODING) {
      return (ThriftDictionaryEncoding)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'encoding' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  /**
   * 
   * @see ThriftDictionaryEncoding
   */
  public void setEncoding(ThriftDictionaryEncoding value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.ENCODING;
    value_ = value;
  }

  public ThriftDictionaryStruct getStructEncoding() {
    if (getSetField() == _Fields.STRUCT_ENCODING) {
      return (ThriftDictionaryStruct)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'structEncoding' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setStructEncoding(ThriftDictionaryStruct value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.STRUCT_ENCODING;
    value_ = value;
  }

  public boolean isSetEncoding() {
    return setField_ == _Fields.ENCODING;
  }


  public boolean isSetStructEncoding() {
    return setField_ == _Fields.STRUCT_ENCODING;
  }


  public boolean equals(Object other) {
    if (other instanceof ThriftDictionaryList) {
      return equals((ThriftDictionaryList)other);
    } else {
      return false;
    }
  }

  public boolean equals(ThriftDictionaryList other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(ThriftDictionaryList other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  /**
   * If you'd like this to perform more respectably, use the hashcode generator option.
   */
  @Override
  public int hashCode() {
    return 0;
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
