/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ambiata.ivory.core.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ThriftDictionaryWindowUnit implements org.apache.thrift.TEnum {
  DAYS(1),
  WEEKS(2),
  MONTHS(3),
  YEARS(4);

  private final int value;

  private ThriftDictionaryWindowUnit(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ThriftDictionaryWindowUnit findByValue(int value) { 
    switch (value) {
      case 1:
        return DAYS;
      case 2:
        return WEEKS;
      case 3:
        return MONTHS;
      case 4:
        return YEARS;
      default:
        return null;
    }
  }
}
